### ISSUE TITLE
Could not initialize class org.blosc.IBloscDll

### ISSUE THREAD

**Issue by wearebk** [glencoesoftware/bioformats2raw#182]
bioformats2raw.bat F:\p\slide-1.mrxs F:\p\_pyramid\s1
2022-12-15 23:25:17,871 [pool-1-thread-1] ERROR c.g.bioformats2raw.Converter - Failure processing chunk; resolution=0 plane=1 xx=70656 yy=38912 zz=0 width=1024 height=1024 depth=1
java.lang.NoClassDefFoundError: Could not initialize class org.blosc.IBloscDll
        at org.blosc.JBlosc.compressCtx(JBlosc.java:213)
        at com.bc.zarr.CompressorFactory$BloscCompressor.compress(CompressorFactory.java:327)
        at com.bc.zarr.chunk.ChunkReaderWriterImpl_Byte.write(ChunkReaderWriterImpl_Byte.java:67)
        at com.bc.zarr.ZarrArray.write(ZarrArray.java:235)
        at com.glencoesoftware.bioformats2raw.Converter.writeBytes(Converter.java:950)
        at com.glencoesoftware.bioformats2raw.Converter.processChunk(Converter.java:1186)
        at com.glencoesoftware.bioformats2raw.Converter.lambda$saveResolutions$4(Converter.java:1376)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by wearebk** [comment]
resolved
