### ISSUE TITLE
ArrayIndexOutOfBoundsException when converting to Zarr

### ISSUE THREAD

**Issue by manics** [glencoesoftware/bioformats2raw#27]
Works:
`bin/bioformats2raw --file_type=zarr "testpixelType=uint8&sizeX=1024&sizeY=1024.fake" out1`
Fails (change `sizeX` from `1024` to `1025`):
`bin/bioformats2raw --file_type=zarr "testpixelType=uint8&sizeX=1025&sizeY=1024.fake" out2`

```
2020-04-20 09:41:19,065 [pool-1-thread-1] INFO  c.g.bioformats2raw.Converter - Successfully processed tile; resolution=0 plane=0 xx=0 yy=0 width=1024 height=1024
2020-04-20 09:41:19,148 [pool-1-thread-2] ERROR c.g.bioformats2raw.Converter - Failure processing tile; resolution=0 plane=0 xx=1024 yy=0 width=1 height=1024
java.lang.ArrayIndexOutOfBoundsException: 1048577
        at net.imglib2.img.basictypeaccess.array.AbstractByteArray.getValue(AbstractByteArray.java:61) ~[imglib2-5.6.3.jar:5.6.3]
        at net.imglib2.type.numeric.integer.GenericByteType.getByte(GenericByteType.java:127) ~[imglib2-5.6.3.jar:5.6.3]
        at net.imglib2.type.numeric.integer.GenericByteType.set(GenericByteType.java:183) ~[imglib2-5.6.3.jar:5.6.3]
        at org.janelia.saalfeldlab.n5.zarr.N5ZarrWriter.padCrop(N5ZarrWriter.java:404) ~[n5-zarr-0.0.2-beta.jar:0.0.2-beta]
        at org.janelia.saalfeldlab.n5.zarr.N5ZarrWriter.writeBlock(N5ZarrWriter.java:433) ~[n5-zarr-0.0.2-beta.jar:0.0.2-beta]
        at org.janelia.saalfeldlab.n5.zarr.N5ZarrWriter.writeBlock(N5ZarrWriter.java:478) ~[n5-zarr-0.0.2-beta.jar:0.0.2-beta]
        at com.glencoesoftware.bioformats2raw.Converter.processTile(Converter.java:623) ~[bioformats2raw-0.2.0-SNAPSHOT.jar:na]
        at com.glencoesoftware.bioformats2raw.Converter.lambda$saveResolutions$2(Converter.java:752) ~[bioformats2raw-0.2.0-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```

**Comment by chris-allan** [comment]
Closing. Should be fixed with #28 going in and the upstream n5-zarr changes in saalfeldlab/n5-zarr#2 being included in our 0.0.3-SNAPSHOT available on repo.glencoesoftware.com.
