### ISSUE TITLE
Padding Width but not Height

### ISSUE THREAD

**Issue by ilan-gold** [glencoesoftware/bioformats2raw#35]
Hello. Thank you so much for writing this library - it is a huge time-saver and is smooth to deploy.  

I have noticed that the `bioformats2raw` --> `raw2ometiff` pipeline outputs pyramids whose tiles along the outer-band of the height dimensions are not padded but the width outer-band tiles are padded.  I am not sure which step is causing the issue or what is "correct" (padding all the time or not) - anecdotally, I noticed that the height/width seemed to be reported correctly in the logs of this repo's step, but I am not sure.

**To Reproduce:**

Download this [sample tiff](http://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/bioformats-artificial/multi-channel.ome.tif).

Then run:
`bioformats2raw $FILE_PATH/multi-channel.ome.tif $N5_FILE_PATH/n5.pyarmid  --tile_width 20 --tile_height 20 --resolutions 8`
`raw2ometiff $N5_FILE_PATH/n5.pyarmid $OUTPUT_DIR/multi-channel.pyramid.ome.tif --compression=zlib`
(Both from version `0.2.1` of their repo)

For example, in this case, all tiles in the highest-resolution are 20x20 except those along the bottom boundary, which are not.

If you want just the sample output, [here](
https://storage.cloud.google.com/vitessce-demo-data/test-data/test_multi-channel.0.2.1.ome.tif?cloudshell=true) is a download that you can inspect.

Here's a little debugging script I wrote in python to look at that output to confirm - it itself could be wrong so let me know if you spot something but this aligns with what I saw in a client-side tiff library as well:

```python
from skimage.external import tifffile
import zlib

with tifffile.TiffFile('/path/to/pyramid/multi-channel.ome.tif', offset=0) as tif:
    print(tif.pages[0].info())
    #     Page 0: 167x439, uint8, 8 bit, minisblack, adobe_deflate, ome|tiled
    # * 256 image_width (1Q) 439
    # * 257 image_length (1Q) 167
    # * 258 bits_per_sample (1H) 8
    # * 259 compression (1H) 8
    # * 262 photometric (1H) 1
    # * 270 image_description (1110s) b'<?xml version="1.0" encoding="UTF-8"?><OME xm
    # * 277 samples_per_pixel (1H) 1
    # * 284 planar_configuration (1H) 1
    # * 305 software (22s) b'OME Bio-Formats 6.2.1'
    # * 322 tile_width (1H) 20
    # * 323 tile_length (1H) 20
    # * 324 tile_offsets (198Q) (16, 78, 142, 195, 265, 327, 389, 469, 533, 604, 675,
    # * 325 tile_byte_counts (198Q) (62, 64, 53, 70, 62, 62, 80, 64, 71, 71, 66, 66, 
    # * 330 sub_ifds (7Q) (42245, 43443, 44049, 44415, 44765, 45083, 45401)
    # * 339 sample_format (1H) 1
    
    fh = tif._fh
    
    # First row, last tile.
    fh.seek(604)
    read = fh.read(71)
    print([b for b in zlib.decompress(read)].__len__())
    # 400 is the length i.e 20 x 20.
    
    # Last row, last tile
    fh.seek(9543)
    read = fh.read(29)
    print([b for b in zlib.decompress(read)].__len__())
    # 140 is a 7 x 20 tile i.e the 7 in the height dimension, 167.
```

Thanks!

**Comment by cgohlke** [comment]
FWIW, according to TIFF rev 6, `TileWidth` and `TileLength` must be a multiple of 16.

**Comment by ilan-gold** [comment]
Thanks.  I noticed the bug originally using tile size 512.  I will be more careful moving forward.

**Comment by melissalinkert** [comment]
Thanks for catching this, @ilan-gold.  I can reproduce the problem, and a proposed fix is in https://github.com/glencoesoftware/raw2ometiff/pull/25.

**Comment by chris-allan** [comment]
Resolved by glencoesoftware/raw2ometiff#25 and glencoesoftware/raw2ometiff#27.

**Comment by chris-allan** [comment]
Fixes released downstream in 0.2.3:

 * https://github.com/glencoesoftware/raw2ometiff/releases/tag/v0.2.3

**Comment by ilan-gold** [comment]
I think this might have opened up another issue, or not, but I am posting this here for now.  I was only able to get the issue to occur on a very large image (my very small image that I posted here looked OK) so I can't give a reproducible example at the moment (I will see if I can get you the raw data) except to say that it happened on a 50000 x 30000 image with tile size 512 x 512.  I do have logs which very clearly point to one line of code.  In the meantime I'll see if I can get you the reference image.

Image:
<img width="142" alt="Screen Shot 2020-05-19 at 3 27 21 PM" src="https://user-images.githubusercontent.com/43999641/82369859-a8656800-99e5-11ea-9ee3-1e7451d11b0b.png">
<img width="924" alt="Screen Shot 2020-05-19 at 3 27 04 PM" src="https://user-images.githubusercontent.com/43999641/82369862-a8656800-99e5-11ea-8daa-20358829b225.png">
<img width="141" alt="Screen Shot 2020-05-19 at 3 26 50 PM" src="https://user-images.githubusercontent.com/43999641/82369863-a8fdfe80-99e5-11ea-86e7-4b2654ef2bd1.png">

Logs:
```
2020-05-19 19:02:11,154 [pool-1-thread-191] INFO  org.perf4j.TimingLogger - start[1589914931144] time[10] tag[writeTile]
2020-05-19 19:02:11,164 [pool-1-thread-161] INFO  org.perf4j.TimingLogger - start[1589914930978] time[186] tag[writeTile]
2020-05-19 19:02:11,168 [main] INFO  org.perf4j.TimingLogger - start[1589914931144] time[23] tag[getInputTileBytes]
2020-05-19 19:02:11,178 [pool-1-thread-190] INFO  org.perf4j.TimingLogger - start[1589914931018] time[160] tag[writeTile]
2020-05-19 19:02:11,180 [pool-1-thread-192] INFO  org.perf4j.TimingLogger - start[1589914931168] time[11] tag[writeTile]
2020-05-19 19:02:11,194 [main] INFO  org.perf4j.TimingLogger - start[1589914931168] time[26] tag[getInputTileBytes]
2020-05-19 19:02:11,208 [pool-1-thread-165] INFO  org.perf4j.TimingLogger - start[1589914931194] time[13] tag[writeTile]
2020-05-19 19:02:11,223 [main] INFO  org.perf4j.TimingLogger - start[1589914931194] time[28] tag[getInputTileBytes]
2020-05-19 19:02:11,235 [pool-1-thread-193] INFO  org.perf4j.TimingLogger - start[1589914931224] time[11] tag[writeTile]
2020-05-19 19:02:11,254 [main] INFO  org.perf4j.TimingLogger - start[1589914931223] time[30] tag[getInputTileBytes]
2020-05-19 19:02:11,259 [pool-1-thread-194] INFO  org.perf4j.TimingLogger - start[1589914931254] time[4] tag[writeTile]
2020-05-19 19:02:11,289 [main] INFO  org.perf4j.TimingLogger - start[1589914931254] time[35] tag[getInputTileBytes]
2020-05-19 19:02:11,298 [pool-1-thread-186] INFO  org.perf4j.TimingLogger - start[1589914931289] time[8] tag[writeTile]
2020-05-19 19:02:11,314 [main] INFO  org.perf4j.TimingLogger - start[1589914931290] time[23] tag[getInputTileBytes]
2020-05-19 19:02:11,314 [pool-1-thread-191] INFO  org.perf4j.TimingLogger - start[1589914931314] time[0] tag[writeTile]
Exception in thread "pool-1-thread-191" java.lang.ArrayIndexOutOfBoundsException
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.lambda$convertPyramid$0(PyramidFromDirectoryWriter.java:725)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-05-19 19:02:11,343 [main] INFO  org.perf4j.TimingLogger - start[1589914931314] time[28] tag[getInputTileBytes]
2020-05-19 19:02:11,348 [pool-1-thread-161] INFO  org.perf4j.TimingLogger - start[1589914931343] time[5] tag[writeTile]
2020-05-19 19:02:11,375 [main] INFO  org.perf4j.TimingLogger - start[1589914931343] time[31] tag[getInputTileBytes]
2020-05-19 19:02:11,383 [pool-1-thread-190] INFO  org.perf4j.TimingLogger - start[1589914931375] time[8] tag[writeTile]
2020-05-19 19:02:11,404 [main] INFO  org.perf4j.TimingLogger - start[1589914931375] time[29] tag[getInputTileBytes]
2020-05-19 19:02:11,414 [pool-1-thread-192] INFO  org.perf4j.TimingLogger - start[1589914931405] time[9] tag[writeTile]
2020-05-19 19:02:11,432 [main] INFO  org.perf4j.TimingLogger - start[1589914931405] time[26] tag[getInputTileBytes]
2020-05-19 19:02:11,437 [pool-1-thread-165] INFO  org.perf4j.TimingLogger - start[1589914931432] time[4] tag[writeTile]
2020-05-19 19:02:11,469 [main] INFO  org.perf4j.TimingLogger - start[1589914931437] time[32] tag[getInputTileBytes]
2020-05-19 19:02:11,477 [pool-1-thread-193] INFO  org.perf4j.TimingLogger - start[1589914931469] time[7] tag[writeTile]
2020-05-19 19:02:11,494 [main] INFO  org.perf4j.TimingLogger - start[1589914931469] time[24] tag[getInputTileBytes]
2020-05-19 19:02:11,500 [pool-1-thread-194] INFO  org.perf4j.TimingLogger - start[1589914931494] time[5] tag[writeTile]
2020-05-19 19:02:11,531 [main] INFO  org.perf4j.TimingLogger - start[1589914931494] time[36] tag[getInputTileBytes]
2020-05-19 19:02:11,539 [pool-1-thread-186] INFO  org.perf4j.TimingLogger - start[1589914931532] time[7] tag[writeTile]
2020-05-19 19:02:11,571 [main] INFO  org.perf4j.TimingLogger - start[1589914931531] time[39] tag[getInputTileBytes]
2020-05-19 19:02:11,580 [pool-1-thread-195] INFO  org.perf4j.TimingLogger - start[1589914931571] time[9] tag[writeTile]
2020-05-19 19:02:11,597 [main] INFO  org.perf4j.TimingLogger - start[1589914931571] time[26] tag[getInputTileBytes]

…

2020-05-19 19:02:28,012 [pool-1-thread-198] INFO  org.perf4j.TimingLogger - start[1589914948007] time[5] tag[writeTile]
2020-05-19 19:02:28,037 [main] INFO  org.perf4j.TimingLogger - start[1589914948012] time[25] tag[getInputTileBytes]
2020-05-19 19:02:28,038 [pool-1-thread-194] INFO  org.perf4j.TimingLogger - start[1589914948037] time[0] tag[writeTile]
Exception in thread "pool-1-thread-194" java.lang.ArrayIndexOutOfBoundsException
        at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.lambda$convertPyramid$0(PyramidFromDirectoryWriter.java:725)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-05-19 19:02:28,067 [main] INFO  org.perf4j.TimingLogger - start[1589914948037] time[29] tag[getInputTileBytes]
2020-05-19 19:02:28,072 [pool-1-thread-192] INFO  org.perf4j.TimingLogger - start[1589914948067] time[5] tag[writeTile]
2020-05-19 19:02:28,097 [main] INFO  org.perf4j.TimingLogger - start[1589914948067] time[29] tag[getInputTileBytes]
2020-05-19 19:02:28,107 [pool-1-thread-193] INFO  org.perf4j.TimingLogger - start[1589914948097] time[9] tag[writeTile]
2020-05-19 19:02:28,126 [main] INFO  org.perf4j.TimingLogger - start[1589914948097] time[28] tag[getInputTileBytes]
2020-05-19 19:02:28,131 [pool-1-thread-196] INFO  org.perf4j.TimingLogger - start[1589914948126] time[5] tag[writeTile]
2020-05-19 19:02:28,158 [main] INFO  org.perf4j.TimingLogger - start[1589914948126] time[31] tag[getInputTileBytes]
2020-05-19 19:02:28,163 [pool-1-thread-197] INFO  org.perf4j.TimingLogger - start[1589914948158] time[5] tag[writeTile]
2020-05-19 19:02:28,196 [main] INFO  org.perf4j.TimingLogger - start[1589914948158] time[38] tag[getInputTileBytes]
2020-05-19 19:02:28,202 [pool-1-thread-165] INFO  org.perf4j.TimingLogger - start[1589914948196] time[5] tag[writeTile]
2020-05-19 19:02:28,228 [main] INFO  org.perf4j.TimingLogger - start[1589914948196] time[32] tag[getInputTileBytes]
```

**Comment by melissalinkert** [comment]
Can you try running raw2ometiff again with the fix in https://github.com/glencoesoftware/raw2ometiff/pull/27, and see if that helps?

**Comment by ilan-gold** [comment]
Sorry, I should have been clearer.  I was responding directly to Chris' comment about 0.2.3 so I think I ran this using that PR.

**Comment by chris-allan** [comment]
0.2.4 now out with fixes to the above coming in from glencoesoftware/raw2ometiff#29.
