### ISSUE TITLE
Could not create an N5 reader

### ISSUE THREAD

**Issue by tabusaqri** [glencoesoftware/bioformats2raw#40]
Hi,
I'm facing this issue:

Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.glencoesoftware.pyramid.PyramidFromDirectoryWriter@3059cbc): java.lang.RuntimeException: loci.formats.FormatException: Could not create an N5 reader
	at picocli.CommandLine.executeUserObject(CommandLine.java:1792)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2349)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:2284)
	at picocli.CommandLine.call(CommandLine.java:2560)
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.main(PyramidFromDirectoryWriter.java:243)
Caused by: java.lang.RuntimeException: loci.formats.FormatException: Could not create an N5 reader
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:274)
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:86)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	... 9 more
Caused by: loci.formats.FormatException: Could not create an N5 reader
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.initialize(PyramidFromDirectoryWriter.java:460)
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:260)
	... 11 more

**Comment by chris-allan** [comment]
Please attach your full log output rather than a snippet.

**Comment by tabusaqri** [comment]
Hi chris,

It's the full log output.

I'm running bin/raw2ometiff using this version raw2ometiff-0.2.4

Thanks

**Comment by chris-allan** [comment]
Please also include the full command line you are executing. That error is implying that whatever you have passed in as input did not come from `bioformats2raw` or is corrupt in some way.

**Comment by tabusaqri** [comment]
bin/raw2ometiff /Users/tabusaqri/Desktop/test_ome 259N_s3.tif

**Comment by chris-allan** [comment]
Was `/Users/tabusaqri/Desktop/test_ome` created by `bioformats2raw`? Is there a `data.n5` folder inside?

**Comment by tabusaqri** [comment]
No, It's manually created. 

I think we have a problem with the setup steps.  Can you please share the steps or the instructions?

**Comment by chris-allan** [comment]
You must run bioformats2raw on your source data and then raw2ometiff on that output. It is a two step process:

 * https://www.glencoesoftware.com/blog/2019/12/09/converting-whole-slide-images-to-OME-TIFF.html

**Comment by tabusaqri** [comment]
Thanks Chris!
